VERSION 0.6

jena:
    FROM eclipse-temurin:11-jre-jammy
    ARG JENAROOT=/jena
    ENV JENAROOT=$JENAROOT
    WORKDIR $JENAROOT
    RUN curl -fssL "https://dlcdn.apache.org/jena/binaries/apache-jena-4.5.0.tar.gz" | tar xz --strip-components=1
    ENV PATH=$JENAROOT/bin:$PATH
    SAVE ARTIFACT $JENAROOT

json:
    FROM +jena
    COPY query.sparql .
    RUN rsparql --service https://query.wikidata.org/sparql --query query.sparql --results json > result.json
    SAVE ARTIFACT result.json AS LOCAL .
